[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc = "0.6.12"
optimizer = true
optimizer_runs = 999999
evm_version = "istanbul"
fs_permissions = [{ access = "read-write", path = "./"}]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options